#!/bin/bash
## Rmk: IMPORTANT, $0 does not have the same name as the binary Rserve!!!

pid=`pgrep -x Rserve` #`ps -C Rserve -o pid=`

#echo "<<$pid>>"


rservePath=`Rscript -e "cat(system.file(\"libs\",version[[\"arch\"]],\"Rserve\",package=\"Rserve\"))"`

if [ "$rservePath" == "" ]; then
	rservePath=`Rscript -e "cat(system.file(\"Rserve\",package=\"Rserve\"))"`
fi

case $1 in
status)
	if [ "$pid" = "" ]; then
		echo "Rserv is NOT running!"
	else
		echo "Rserv is running!"
	fi
	;;
start)
	if [ "$pid" = "" ]; then
		R CMD $rservePath
		##echo "Rserv started!"
	else
		echo "Rserv already started!"
	fi
	;;
stop)
	if [ "$pid" = "" ]; then
		echo "Rserv already stopped!"
	else
		kill $pid 
		echo "Rserv stopped!"
	fi
	;;
esac
